import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import LayoutSlice from "@/appPages/components/layout/LayoutSlice";
import RootLayoutClient from "./layout.client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EduHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayoutClient>
          <LayoutSlice>{children}</LayoutSlice>
        </RootLayoutClient>
      </body>
    </html>
  );
}
